### ISSUE TITLE
freeze email field issue?

### ISSUE THREAD

**Issue by ghost** [DavyJonesLocker/client_side_validations#570]
I'm using:
client_side_validations (3.2.5)
rails 3.2.12

If I tab over the email field  (thereby showing the inline error), and then If I go back and fill out the error email field then the inline error does not disappear for the email field. It will disappear on all other fields I go back and fill out but not email. 

If I partially fill out the email field and get an error, then yes it will let me correct it and submit. It only fails completely if I tab past the email field without putting anything in it.

I also tested it by removing the email validation completely from the model. When this is removed is software works as it should.

Also,  I can't clear the error or submit (obviously) when this happens. Any ideas on this?

Model validation code:
 validates :email,
              :format => { :with => /\b[A-Z0-9._%a-z-]+@(?:[A-Z0-9a-z-]+.)+[A-Za-z]{2,4}\z/ }

**Comment by tagliala** [comment]
Hi,

I'm shutting down old issues.

If it still is an issue, feel free to open a new one but make sure it [meets our Contributing Guidelines](https://github.com/DavyJonesLocker/client_side_validations/blob/master/CONTRIBUTING.md#submitting-a-new-issue)

Maybe this was caused by the syncronous ajax call to the uniqueness middleware
