### ISSUE TITLE
numericality comma gotcha

### ISSUE THREAD

**Issue by taavo** [DavyJonesLocker/client_side_validations#573]
By default, the c_s_v numericality regex permits commas, in the appropriate positions (e.g. "1,000,000"), but rails' numericality validator doesn't.

This is clearly intentional, so I haven't included a pull request, but... what's the deal? It means c_s_v numericality doesn't really work unless you include code on the server to strip out the commas.

This would change some long-standing behavior if you made the change in the 3.2 branch, so I can see an argument against it there, but you may want to reconsider it for 4.0.

**Comment by tagliala** [comment]
Hi,

I'm shutting down old issues.

If it still is an issue, feel free to open a new one but make sure it [meets our Contributing Guidelines](https://github.com/DavyJonesLocker/client_side_validations/blob/master/CONTRIBUTING.md#submitting-a-new-issue)

I've switched to proper SemVer because of this
