### ISSUE TITLE
client_side_validation  with devise 

### ISSUE THREAD

**Issue by aditya01933** [DavyJonesLocker/client_side_validations#595]
When I am installing client_side_validation in my project its giving error

ArgumentError in Devise::Sessions#new
wrong number of arguments (3 for 2)
in 
<%= form_for(resource, :as => resource_name, :url => registration_path(resource_name)) do |f| %>
Its working fine if I am removing gem client_side_valiation from my gem file. I tried searching on stackoverflow but not working. Thanks in advance.

**Comment by tagliala** [comment]
please provide more information, take another look at our contributing guidelines: https://github.com/DavyJonesLocker/client_side_validations/blob/master/CONTRIBUTING.md#submitting-a-new-issue

Since the last released gem (3.2.6) is unmantained, please make sure you are pointing to the master branch:

```rb
gem 'client_side_validations', github: 'DavyJonesLocker/client_side_validations'
```

**Comment by dmur** [comment]
Since a lot of people seem to be having this issue (I encountered it as well), perhaps some prominent documentation that the released gem is no longer maintained would be in order?

**Comment by tagliala** [comment]
@dmur I need to release a new version but I'm having a busy time, sorry
