### ISSUE TITLE
is_unique? check fails on MySQL and probably other storage engines

### ISSUE THREAD

**Issue by muffinista** [DavyJonesLocker/client_side_validations#636]
In 3.2.7, ClientSideValidations::ActiveRecord::Middleware generates a SQL query that uses syntax which doesn't work in MySQL, and possibly other engines (I've only found matching syntax in Oracle):

The query is generated [here](https://github.com/DavyJonesLocker/client_side_validations/blob/master/lib/client_side_validations/active_record/middleware.rb#L22)

```
 sql << "#{t[attribute].matches(escaped_value).to_sql} ESCAPE '\\'"
```

This generates a query along the lines of:

```
SELECT 1 AS one FROM `pages`
WHERE (`pages`.`title` LIKE 'Schedule' ESCAPE '\' ) LIMIT 1
```

Which returns the error:

```
Mysql2::Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''\'' at line 1: SELECT  1 AS one FROM `pages`  WHERE (`pages`.`title` LIKE 'Schedule' ESCAPE '\') LIMIT 1
```

(NOTE: I've trimmed some sensitive data from these queries but I don't believe it to be relevant)

As I understand it, there is no ESCAPE clause in SELECT queries in MySQL.

Rolling back to 3.2.6 fixes the problem for me, and I'm not entirely sure what the intent is here, so I don't have a fix/PR to suggest.

**Comment by tagliala** [comment]
Sorry for the poor testing.

I must remove the uniqueness validator. There are security concerns (information disclosure). If you roll back to 3.2.6 please disable the uniqueness validator

**Comment by blimey85** [comment]
I think this is a fairly significant issue as testing for uniqueness is a very common need. How I've handled it in the past is to have a method in my controller that can check whichever field I need. Typically that's username and email address. So I post something like type=name, name=bob, and it returns true or false. Now that I'm updating one of my projects to use ClientSideValidations, I like the idea of having this built in, or at the very least, an easy way to tie into my own controller method.

Maybe since it's a security issue and you don't want the functionality built into the gem any longer, you could add a method so that in the initializer we could set the path to our own method and then when CSV hits a uniqueness validation it checks the initializer based on controller and field and then fires a request to that method.

I really like that CSV has everything neat and tidy and I don't have any ajax littering my view which is how my previous setup has worked. Question... is this ONLY an issue with MySQL? I use MySQL, or MariaDB to be more specific, so even if it is just the one db it would still affect me but I'm curious if it's a MySQL issue or an issue with how the code is setup.

**Comment by tagliala** [comment]
@blimey85 I really don't want this method inside CSV. It opens to information disclosure and I don't know how to fix this. I've also tried to run tests on travis against different DBs so I could take track of ORM-specific issues. 

Here it is the code: https://github.com/DavyJonesLocker/client_side_validations/blob/master/lib/client_side_validations/active_record/middleware.rb#L19

feel free tu submit a PR with a fix.
