### ISSUE TITLE
Problem with js_regex dependency gem within AWS ElasticBeanstalk

### ISSUE THREAD

**Issue by iFurt** [DavyJonesLocker/client_side_validations#643]
rake assets:precompile raises error :
rake aborted!
  LoadError: cannot load such file -- js_regex
  /var/app/ondeck/config/application.rb:12:in `<top (required)>'
  /var/app/ondeck/Rakefile:4:in `require'
  /var/app/ondeck/Rakefile:4:in `<top (required)>'
  /opt/elasticbeanstalk/support/scripts/check-for-rake-task.rb:21:in `<main>'
  (See full trace by running task with --trace)

And puma's logs:
...
/opt/rubies/ruby-2.0.0-p647/lib/ruby/gems/2.0.0/gems/activesupport-4.0.2/lib/active_support/dependencies.rb:229:in `require': cannot load such file -- js_regex (LoadError)
...

This error is present only within AWS EB . It works fine locally and within Heroku.

**Comment by tagliala** [comment]
@janosch-x any hint?

**Comment by janosch-x** [comment]
Seems js_regex hasn't been installed. Right now I don't see how this could have anything to do with js_regex or the way it's referenced in client_side_validations. It's probably more of an AWS EB issue. @iFurt you could `eb ssh` onto the server and run `gem list js_regex -i`. That will print out whether js_regex is installed or not. If it's not installed, perhaps you can install it manually with `gem install js_regex`. There's also some stuff on SO that deals with gem/bundler problems on AWS EB: http://stackoverflow.com/questions/13642171/

**Comment by iFurt** [comment]
Yeap, I've installed it manually during ssh session. Now gem list js_regex -i returns true. Trying to solve the problem with customizing .ebextension dir as described in http://stackoverflow.com/questions/13642171/ 
Thank you for pointing direction to work on.

**Comment by iFurt** [comment]
Problem solved with transfering js_regex gem to vendor dir of my app. Thank you for help.

**Comment by tagliala** [comment]
Glad you solved

I'm asking if `bundle` is not supposed to solve this... I mean, I don't have this issue on heroku/mina based deploys

**Comment by iFurt** [comment]
Yes, within Heroku it works fine with bundle. The problem seems to be with AWS EB when gem is a git repo.

**Comment by tagliala** [comment]
@iFurt you can use the new released 4.2.0 gem instead of pointing to the master branch
