### ISSUE TITLE
Pre-filled form appears as valid

### ISSUE THREAD

**Issue by PierreGUI** [DavyJonesLocker/client_side_validations#703]
Hello, first thanks a lot for your amazing work!

I have an issue where form appears to be completely valid when it's pre-filled with incomplete data.
Means all the inputs in the form appears valid, even the empty ones (empty isn't valid).
We sometimes get to create a form which is pre-filled with all we know about a user, but some info still are to be filled by the user then.
Validation works perfectly usually on an empty form. Only when form model exists already and some values are pre-filled then the issue appears.

### Versions
`client_side_validations 9.3.1`
`client_side_validations-simple_form 6.2.0`
`Rails 5.0.1`

### Model validation (nothing fancy)
```
  validates          :name,         presence: true
  validates_email    :email
  validates          :email,        presence: true
  validates_phone    :phone
  validates          :phone,        presence: true, allow_blank: false
  validates          :address,      presence: true
  validates          :city,         presence: true
  validates          :country_code, presence: true
```

### Template snippet (uses simple_form)
```
= simple_form_for @checkout, url: url, html: { method: method, id: "edit_checkout" }, validate: true, wrapper: :checkout do |co|
  = co.input :name, label: t("label.fullname"), class: "name"
  = co.input :email, label: t("label.email_address")
  = co.input :phone, label: t("label.phone_number"), class: "phone"

  = co.input :country_code, priority: Order.popular_countries(5), selected: @checkout.country_code, label: t("label.country"), validate: false, required: false

  .row.checkout-inline
    = co.input :city, label: t("label.city"), wrapper: :checkout_inline, wrapper_html: { class: "city col-sm-7" }
    = co.input :zip, label: t("label.postcode"), required: true, wrapper: :checkout_inline, wrapper_html: { class: "zip col-sm-5" }

  = co.input :address, label: t("label.address")
```

### Rendered HTML (seems OK)
I have no doubt this works, since an empty form is being validated correctly. Only when `@checkout` form model object has some attributes filled then whole form appears as valid.
Rendered html is [on pastebin.com](https://pastebin.com/un980N1L)

### Attached image
![issue](https://cloud.githubusercontent.com/assets/1013904/25948292/1d22e432-3653-11e7-85ff-718fd3e3085c.jpg)

Thanks for your help.

**Comment by tagliala** [comment]
Hi,

Thanks for the detailed information.

CSV issues are hard to debug and extremely time consuming to investigate.

The postcode from your html is already filled with the value `1071KB`
```html
        <input class="form-control string required" required="required" aria-required="true" type="text" value="1071KB" name="checkout[zip]" id="checkout_zip" data-validate="true">
```

Address is empty indeed.

Unfortunately I cannot understand when the issue appear, since there isn't an automatic error checking when displaying the form fields.

I'm only getting a "can't be blank" issue when blurring the address field.

I'm asking you if you could provide a reduced test case hosted on github and a step-by-step guide to reproduce the issue. Example: https://github.com/ghaydarov/CSV-CW

**Comment by PierreGUI** [comment]
Hi,
Thanks for answering so quick.
Indeed screenshot mismatches with HTML (forgot to hide postcode there). Issue shows whatever field is empty or not :(

I'll take some time to produce an example app, hopefully it'd be as simple as:
1. Make a form attached to a model
2. Complete the form, validate the model
3. Tweak model by removing some attributes values then inject back in form

Then the issue should appear.
Cheers

**Comment by tagliala** [comment]
@PierreGUI 

Sorry but as I mentioned bifore, debug non-trivial issues with CSV is quite hard and time consuming.

The best you can do to help me replicate the issue is to provide actual application with a reduced test case (just the gems, models, controllers, views, fields, javascript needed to reproduce the issue), hosted on github, with a valid model (again, just the fields needed to reproduce the issue) and its dummy data (loaded via db:seed) and a step to step guide to reproduce the issue.

Example of application:  https://github.com/ghaydarov/CSV-CW
Example of step-to-step guide for the above application: https://github.com/DavyJonesLocker/client_side_validations/issues/694#issuecomment-277825798

Other steps to steps guide to reproduce issues: https://github.com/DavyJonesLocker/client_side_validations/issues/687#issuecomment-274350351, https://github.com/DavyJonesLocker/client_side_validations/issues/687#issuecomment-274351991

**Comment by PierreGUI** [comment]
Hey, thanks again for your time helping with this.
As I was creating a project to demonstrate the issue ([here it is](https://github.com/PierreGUI/CSV-isValid)), I managed to understand the issue better.

What happens is I run a validation on the form on page load, m
What it does is show all fields as valid:
`$("form#checkout").isValid(ClientSideValidations.validators)` ([checkout.js#L8](https://github.com/PierreGUI/CSV-isValid/blob/master/app/assets/javascripts/checkouts.js#L8))

**Comment by tagliala** [comment]
@PierreGUI sorry for the late reply

Please try

```js
  $("form#checkout").isValid($("form#checkout")[0].ClientSideValidations.settings.validators)
```

**Comment by PierreGUI** [comment]
Awesome it works!
Thanks a lot for your help :)

**Comment by tagliala** [comment]
You're welcome.

I've also updated this wiki: https://github.com/DavyJonesLocker/client_side_validations/wiki/Manually-trigger-input-validation
