### ISSUE TITLE
Issue with only_integer: true numericality validator

### ISSUE THREAD

**Issue by wasif-saeed-confiz** [DavyJonesLocker/client_side_validations#717]
Hi i am using a validation numericality: 
```
{greater_than: 0, less_than_or_equal_to: 2_147_483_647, only_integer: true}
```
Problem is that client side js allows user to add , separated format but server side validation give error message. 

> Not A Number.

**Comment by tagliala** [comment]
> Problem is that client side js allows user to add , separated format but server side validation give error message.

![image](https://user-images.githubusercontent.com/556268/29919366-50e5426c-8e49-11e7-9c48-fb5a853662ec.png)

![image](https://user-images.githubusercontent.com/556268/29919391-62832dc2-8e49-11e7-9555-f1ce248b0eb1.png)

Cannot confirm, closing here.

Debugging CSV issues is time consuming. Please provide all the details required by the [contributing guidelines for new issues](https://github.com/DavyJonesLocker/client_side_validations/blob/master/CONTRIBUTING.md#submitting-a-new-issue)

**Comment by wasif-saeed-confiz** [comment]
@tagliala  add number with proper format like 10,000 i have debug and came to know that there is issue in js level validation. js allows user to add numbers in properly , formatted. but rails did not allow.

**Comment by wasif-saeed-confiz** [comment]
try your code with 10,000 value.

**Comment by tagliala** [comment]
Replicated, thanks.

I suppose that this is an expected behaviour to deal with localization and I'm not confident in removing this feature.

The current implementation of CSV allows users to submit values like `123,45`, which is the same of `123.45` here in Italy and in some other European countries.

This will also allow user to better display long integers.

Eg:

1. User inserts a product with the price of: `10.500` (or `10'500`, `10,000`)
2. The server to normalizes the above input (by overriding the `price=` assignment operator)
3. User wants to edit the above product, the form could show the above number as `10.500` (or `10'500` or `10,500`, according to country and number format)

Fortunately, there is a couple of easy workaround:

A. Change the validation
```rb
  validates :number_717, numericality: { greater_than: 0, less_than_or_equal_to: 2_147_483_647 }, format: { with: /\A[+-]?\d+\z/, message: :not_an_integer }
```

or 

B. Use a [number field](http://caniuse.com/#feat=input-number) (IE10+)
```erb
    <%= f.number_field :number_717 %>
```

Refs:
- https://github.com/mdeering/attribute_normalizer

Hope it helps, closing here

**Comment by wasif-saeed-confiz** [comment]
@tagliala Thanks for your help. : ) will try this out.

**Comment by tagliala** [comment]
@wasif-saeed-confiz I'm considering to rewrite this feature in CSV 10.

I think that the principle of least surprise would be preserved when client side validations act like server side validations.

So, `only_integer: true` option should not allow for `.` and `,` by default, as per [Active Model's numericality validator](https://github.com/rails/rails/blob/47eadb68bfcae1641b019e07e051aa39420685fb/activemodel/lib/active_model/validations/numericality.rb#L82).

It should also not allow for delimiters

I will just keep the option to get the decimal separator from `I18n` locale.

What do you think?

**Comment by wasif-saeed-confiz** [comment]
What would be great because everyone things server side validation should match with client side validation.

**Comment by tagliala** [comment]
Hi @wasif-saeed-confiz, please give a try to the master branch

**Comment by wasif-saeed-confiz** [comment]
Currently i am busy with the production. I will try this in next sprint. Thanks
