### ISSUE TITLE
TypeError: $(...).enableClientSideValidations is not a function

### ISSUE THREAD

**Issue by radvc** [DavyJonesLocker/client_side_validations#719]
I don't know why Im getting this but before my validation in modal is working, also in my other projects validation is working.

**Comment by radvc** [comment]
I already fix my problem, Thanks!

**Comment by NirvashType0** [comment]
Hey man! Im trying to enable inline client side validations on my project with modals but at the moment the only thing I get succesfull is the fact that the forms are not submited because they does not pass the validation but no inline errors showing, I really need help, maybe you can show me the way you create your modals and how use the gem for modals! TY
