### ISSUE TITLE
can any one give me a tip to add css modicications when using this gem

### ISSUE THREAD

**Issue by pasanrox** [DavyJonesLocker/client_side_validations#727]
### Expected behavior*
Tell us what should happen

### Actual behavior*
Tell us what happens instead

### System configuration*
**Rails version**:

**Ruby version**:

**Client Side Validations version**:

### Browser's development console output*
_Please confirm that your browser's development console does not contain errors._

### Additional JavaScript Libraries*
_If your issue depends on other JavaScript libraries, please list them here. E.g: *Bootstrap Modal v3.3.7, jQuery UI Datepicker 1.12.4*._

### Repository demostrating the issue

---

**\*** Failure to include this requirement will result in the issue being closed.

**Comment by tagliala** [comment]
Hi,

could you please fix this report?

1. Provide a shorter, better title
2. Explain your question. Since this is not an issue report, please remove the issue template and explain what you need

Please take a look at this readme section, maybe this is what you are looking for: https://github.com/DavyJonesLocker/client_side_validations#customize-error-rendering

Meanwhile, closing here.

Feel free to comment, I will definitely read here
