### ISSUE TITLE
Is this gem available as a CDN link?

### ISSUE THREAD

**Issue by viktorsmari** [DavyJonesLocker/client_side_validations#751]
Instead of using it 'the rails way' using the asset pipeline.

Something like adding  
`<%= javascript_include_tag "https://code.jquery.com/jquery-3.3.1.min.js" %>`
in `application.html.rb`

**Comment by tagliala** [comment]
Hi!

Thanks for being part of the Client Side Validations Community.

Given that you need the gem because it needs to monkey patch the rails `form_for` method, if you want the javascript port of CSV to be hosted on a CDN, please let me know if there is a service which does this for free and I will try to help you

**Comment by tagliala** [comment]
Meanwhile, closing here
