### ISSUE TITLE
Not working with Nested fields

### ISSUE THREAD

**Issue by nomadcoder87** [DavyJonesLocker/client_side_validations#764]
Same problem
- Rails 5.2.1
- client_side_validations 15.0.0
- simple_form 4.0.1
- client_side_validations-simple_form 7.0.0

I have a form of a Driver model, nested with references, and documents, it's a wizard form wich loads enterily(not dinamicly), the first part of the form with the basic info of the Driver works perferct but the References and Documents part doesn't generates the validators.

Tried a lot of solutions but i guess only works with old rails versions, hope you can help me, thanks

**Comment by tagliala** [comment]
Hi,

thanks for being part of the CSV community

Debugging CSV issues is a time consuming task and demands a lot of effort on my side, because CSV it's using the validation settings from one (or more, as in this case) models, views, JavaScript configuration, and rendered output html

Anyway, to speed up things, I've pushed a new bug report template.

Please fill it out, or edit the first post here and ping me: https://github.com/DavyJonesLocker/client_side_validations/issues/new?assignees=&labels=&template=bug_report.md&title=

Meanwhile, closing here
